version: '3.8'

services:
  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: "Abc@12345"
    ports:
      - "15432:5432"
    volumes:
      - ms-email-data:/var/lib/postgresql/data 
    networks:
      - ms-email-network
      
  pgadmin:
    image: dpage/pgadmin4:6.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@tests.cams7.br"
      PGADMIN_DEFAULT_PASSWORD: "Abc@12345"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - ms-email-network
      
  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - ms-email-network

networks: 
  ms-email-network:
    driver: bridge

volumes:
  ms-email-data:
